# Generated by Django 4.1 on 2022-09-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='タグ名'),
        ),
    ]
