# Generated by Django 4.1 on 2022-09-07 08:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='画像'),
        ),
    ]
