# Generated by Django 4.1 on 2022-09-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0003_question_no_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
