# Generated by Django 4.1 on 2022-09-08 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nnkr', '0003_alter_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbychatLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lobbychat',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='like_lobbycahts', through='nnkr.LobbychatLike', to=settings.AUTH_USER_MODEL, verbose_name='いいねした人'),
        ),
        migrations.AddField(
            model_name='lobbychatlike',
            name='lobbychat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nnkr.lobbychat'),
        ),
    ]
