# Generated by Django 4.1 on 2022-09-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, verbose_name='タグ名'),
        ),
    ]
