# Generated by Django 4.1 on 2022-09-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0004_lobbychatlike_lobbychat_likers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', through='nnkr.Tagging', to='nnkr.tag', verbose_name='タグ'),
        ),
    ]
