# Generated by Django 4.1 on 2022-08-28 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nnkr', '0004_delete_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', through='nnkr.Bookmark', to=settings.AUTH_USER_MODEL, verbose_name='ブックマーカー'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nnkr.question'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
