# Generated by Django 4.1 on 2022-09-04 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('nnkr', '0004_comment_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', through='nnkr.Liker', to=settings.AUTH_USER_MODEL, verbose_name='イイねしたユーザー'),
        ),
        migrations.AddField(
            model_name='liker',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nnkr.question'),
        ),
        migrations.AddField(
            model_name='liker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
