# Generated by Django 4.1 on 2022-09-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=32, unique=True, verbose_name='タグ名')),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='タグ名'),
        ),
    ]
