# Generated by Django 4.1 on 2022-08-30 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0005_bookmark_question_bookmarkers_bookmark_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nnkr.question', verbose_name='対象質問'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', through='nnkr.Tagging', to='nnkr.tag', verbose_name='タグ'),
        ),
    ]
