# Generated by Django 4.1 on 2022-09-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0005_tag_slug_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
