# Generated by Django 4.1 on 2022-09-04 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('nnkr', '0005_liker_question_likers_liker_question_liker_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disliker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='dislikes', through='nnkr.Disliker', to=settings.AUTH_USER_MODEL, verbose_name='否定したユーザー'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='likes', through='nnkr.Liker', to=settings.AUTH_USER_MODEL, verbose_name='評価したユーザー'),
        ),
        migrations.AddField(
            model_name='disliker',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nnkr.question'),
        ),
        migrations.AddField(
            model_name='disliker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
