# Generated by Django 4.1 on 2022-09-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0007_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagging',
            options={'ordering': ('id',)},
        ),
    ]
