# Generated by Django 4.1 on 2022-09-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0008_alter_tagging_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagging',
            options={'ordering': ('tagging_datetime',)},
        ),
    ]
