# Generated by Django 4.1 on 2022-09-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0008_question_tweet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tweet_id',
        ),
    ]
