# Generated by Django 4.1 on 2022-09-06 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nnkr', '0008_remove_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='発言日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('text', models.TextField(verbose_name='本文')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loby_chats', to=settings.AUTH_USER_MODEL, verbose_name='発言者')),
            ],
        ),
    ]
