# Generated by Django 4.1 on 2022-09-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0009_lobbychat'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='更新されたか'),
        ),
        migrations.AddField(
            model_name='lobbychat',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='更新されたか'),
        ),
    ]
