# Generated by Django 4.1 on 2022-09-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0010_alter_tagging_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagging',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging', to='nnkr.tag'),
        ),
    ]
