# Generated by Django 4.1 on 2022-09-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0011_alter_tagging_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagging',
            options={'ordering': ('tagging_datetime',)},
        ),
    ]
