# Generated by Django 4.1 on 2022-10-10 14:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(default=1, verbose_name='コメントID')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='発言日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_updated', models.BooleanField(default=False, verbose_name='更新されたか')),
                ('text', models.TextField(verbose_name='本文')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('description', models.TextField(verbose_name='説明文')),
                ('paifudata', models.JSONField(verbose_name='牌譜データ')),
                ('seat', models.IntegerField(choices=[(0, 'East'), (1, 'South'), (2, 'West'), (3, 'North')], default=0, verbose_name='席')),
                ('release', models.IntegerField(choices=[(0, '一般公開'), (1, '限定公開(URLを知っている人だけ)'), (2, '非公開')], default=0, verbose_name='公開範囲')),
            ],
        ),
        migrations.CreateModel(
            name='Kyoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='局名')),
                ('paifu', models.CharField(max_length=9000, verbose_name='牌譜')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyokus', to='kntu.examination', verbose_name='対象検討')),
            ],
        ),
    ]
