# Generated by Django 4.1 on 2022-10-10 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('kntu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kntu.comment'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_comment_likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_comments', to=settings.AUTH_USER_MODEL, verbose_name='発言者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='kyoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kntu.kyoku', verbose_name='対象局'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='like_exam_comments', through='kntu.CommentLike', to=settings.AUTH_USER_MODEL, verbose_name='いいねした人'),
        ),
    ]
