# Generated by Django 4.1 on 2022-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='order',
            field=models.IntegerField(default=0, verbose_name='順番'),
        ),
    ]
