# Generated by Django 3.2.5 on 2022-08-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnkr', '0003_bookmark'),
        ('user', '0002_auto_20220823_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, through='nnkr.Bookmark', to='nnkr.Question', verbose_name='ブックマーク'),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
